### PR TITLE
feat: add channel sidebar styles

### PR DESCRIPTION
**Pull request by zax-xyz**
Still needs a few more changes, for instance the selected channel style and minor margin differences

### CODE REVIEW

**Comment by Snazzah** [comment]
Pings are taking the place over unreads

**Comment by ThatTonybo** [comment]
image
Discord puts mentions on the other side

**Comment by zax-xyz** [comment]
That issue should be fixed now. It doesn't have the number of pings on it so it's still not exactly the same, but there isn't really anything we can do about that

**Comment by ThatTonybo** [comment]
Yeah, bit weird that the server icon itself shows the number of mentions, yet individual channels fail to. Looks good though.

**Pull request merged**
